### Get all assignments
GET {{baseMaestroUrl}}:{{maestroPort}}/api/assignments

### Get assignment by ID
GET {{baseMaestroUrl}}:{{maestroPort}}/api/assignments/<ID>

### Create a new assignment
POST {{baseMaestroUrl}}:{{maestroPort}}/api/assignments
Content-Type: application/json

{
  "name": "New Assignment",
  "modelName": "Model1",
  "maestroPort": 8080,
  "gpuIds": [1, 2]
}

### Delete an assignment
DELETE {{baseMaestroUrl}}:{{maestroPort}}/api/assignments/<ID>

### Deploy all assignments
POST {{baseMaestroUrl}}:{{maestroPort}}/api/assignments/deployAll

### Update an assignment
PUT {{baseMaestroUrl}}:{{maestroPort}}/api/assignments/<ID>
Content-Type: application/json

{
  "name": "Updated Assignment",
  "modelName": "Model2",
  "maestroPort": 8081,
  "gpuIds": [2, 3]
}
