### Get all assignments
GET {{maestroHost}}/api/assignments

### Get assignment by ID
GET {{maestroHost}}/api/assignments/<ID>

### Create a new assignment
POST {{maestroHost}}/api/assignments
Content-Type: application/json

{
  "name": "New Assignment",
  "model_name": "Model1",
  "maestroPort": 8080,
  "gpu_ids": [1, 2]
}

### Delete an assignment
DELETE {{maestroHost}}/api/assignments/<ID>

### Deploy all assignments
POST {{maestroHost}}/api/assignments/deployAll

### Update an assignment
PUT {{maestroHost}}/api/assignments/<ID>
Content-Type: application/json

{
  "name": "Updated Assignment",
  "modelName": "Model2",
  "maestroPort": 8081,
  "gpu_ids": [2, 3]
}
