### Get all computers
GET {{maestroHost}}/api/computers

### Get computer by ID
GET {{maestroHost}}/api/computers/<ID>

### Create a new computer
POST {{maestroHost}}/api/computers
Content-Type: application/json

{
  "name": "New Computer",
  "ipAddr": "0.0.0.0"
}

### Delete an computer
DELETE {{maestroHost}}/api/computers/<ID>

### Update an computer
PUT {{maestroHost}}/api/computers/1
Content-Type: application/json

{
    "id": 1,
    "name": "3090 Cluster - 1",
    "ip_addr": "192.168.1.32",
    "edge_server_port": 4000,
    "display_order": 1
  }
