### Get all computers
GET {{baseMaestroUrl}}:{{maestroPort}}/api/computers

### Get computer by ID
GET {{baseMaestroUrl}}:{{maestroPort}}/api/computers/<ID>

### Create a new computer
POST {{baseMaestroUrl}}:{{maestroPort}}/api/computers
Content-Type: application/json

{
  "name": "New Computer",
  "ipAddr": "0.0.0.0"
}

### Delete an computer
DELETE {{baseMaestroUrl}}:{{maestroPort}}/api/computers/<ID>

### Update an computer
PUT {{baseMaestroUrl}}:{{maestroPort}}/api/computers/<ID>
Content-Type: application/json

{
  "name": "Updated Computer",
  "ipAddr": "0.0.0.1"
}
