### Get all gpus
GET {{baseMaestroUrl}}:{{maestroPort}}/api/gpus

### Get gpu by id
GET {{baseMaestroUrl}}:{{maestroPort}}/api/gpus/<ID>

### Create a new gpu
POST {{baseMaestroUrl}}:{{maestroPort}}/api/gpus
Content-Type: application/json

{
  "name": "New GPU",
  "vram_size": 4,
  "computer_id": 123,
  "weight": 1
}

### Delete a gpu
DELETE {{baseMaestroUrl}}:{{maestroPort}}/api/gpus/<ID>

### Update a gpu
PUT {{baseMaestroUrl}}:{{maestroPort}}/api/assignments/<ID>
Content-Type: application/json

{
  "name": "Updated GPU",
  "vram_size": 4.3,
  "computer_id": 123,
  "weight": 15
}
