### Get all models
GET {{maestroHost}}/api/models

# type param = llm, diffusor, stt, or tts

### Get model by name
GET {{maestroHost}}/api/models/<NAME>?type=<TYPE>

### Create a new model
POST {{maestroHost}}/api/models
Content-Type: application/json

{
  "name": "New Model",
  "size": 4
}

### Delete a model
DELETE {{maestroHost}}/api/models/<NAME>?type=<TYPE>
